### ISSUE TITLE
Image smoothing for training

### ISSUE THREAD

**Issue by RahulGalda** [RenYurui/StructureFlow#5]
hi, does it work if I use a Gaussian filter from python for smoothing the images instead of the matlab code that you have? or any other suggestions as I dont want use matlab separately everytime

**Comment by RenYurui** [comment]
If you want to train the model with Gaussian smoothed image labels, it may be feasible. But I think the performance will be degraded, since the recovered structure images do not contain sharp edges.

Maybe you can generate the smooth images for your entire test set to avoid using MATLAB everytime.
Or maybe you can try to convert the MATLAB smooth code to python.

**Comment by RahulGalda** [comment]
thanks, one script is missing in matlab files. "tsmooth" can you share the script

**Comment by RenYurui** [comment]
Please follow the instruction in the Readme.md and download it from http://www.cse.cuhk.edu.hk/~leojia/projects/texturesep/
